### ISSUE TITLE
Incorrect statement on blog post...

### ISSUE THREAD

**Issue by PatchworkBoy** [rossharper/boilercontrol#2]
Just a quick correction to your blog post at http://rossharper.net/2015/11/decoding-a-siemens-rcr10433-thermostat-signal-to-control-a-boiler-from-a-raspberry-pi/ where you state...

> Now we can see that:
> the first 31 bits of the packet (excluding the start bit again) are the same in both the ON and OFF signals...

Not quite correct, as they AREN’T the same with my Siemens RCR10/433-GB... here’s the data sniffed from mine (note the 10th bit):

> ON packet pair
> {1,0,0,0,1,1,0,0,0,**0**,1,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1},
> {1,1,1,1,0,0,1,1,1,**1**,0,1,1,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0}
> 
> OFF packet pair
> {1,0,0,0,1,1,0,0,0,**1**,1,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0},
> {1,1,1,1,0,0,1,1,1,**0**,0,1,1,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1}

I also had to re-do the timings as mine appeared significantly different to yours (mine needed to be drastically shorter). Once those were set, all works peachy - I now have it mapped to a virtual switch in Domoticz, and am voice controlling it with Siri via HomeBridge with eDomoticz plugin. Ta muchly for the scripts!

**Comment by rossharper** [comment]
Interesting. Thanks for raising it. I'll amend my post. 

Your voice control via Siri implementation sounds interesting too... I think I'll have to look into that!

**Comment by rossharper** [comment]
Blog post updated to reflect @PatchworkBoy's findings.
